### PR TITLE
Allow to use Representable 3.1+

### PR DESCRIPTION
**Pull request by jandudulski**
Replace Virtus with Dry-Types to make Roar compatible with Representable 3.1

Resolves #217, resolves #222

### CODE REVIEW

**Review by yogeshjain999 — APPROVED** [review]
Thanks @jandudulski, looking good to me!

**Comment by jandudulski** [comment]
@yogeshjain999 thank you. Can we merge & release? :)

**Review by apotonick — APPROVED** [review]
Looking good to me, although I could swear there was a similar commit somewhere... :v:

**Comment by jandudulski** [comment]
@apotonick yes, I mentioned them in PR. This PR is kind of merge of them and update :wink:

**Comment by yogeshjain999** [comment]
@apotonick should we release this change as `1.2.0` ?

**Comment by jandudulski** [comment]
@yogeshjain999 @apotonick please also release a new version of roar-rails so we can use it with the new version of roar :) https://github.com/apotonick/roar-rails/pull/141

**Comment by apotonick** [comment]
Definitelty 1.2.0! :metal:

**Comment by jandudulski** [comment]
@yogeshjain999 can you please also add a new tag and release to rubygems? :)

**Comment by yogeshjain999** [comment]
@jandudulski done 🍻

**Pull request merged**
