### PR TITLE
Mason support

### PR DESCRIPTION
**Pull request by azurastar**
Adds support for Mason namespaces and controls. 

TO-DO: 
- meta
- errors

Early feedback appreciated. Team effort at Zipcar by @azurastar, @cabm, @HollyM021980, @paulswartz, @ivojinovic, @rachelrudolph8, & @elephino

### CODE REVIEW

**Comment by cabm** [comment]
Thanks for your quick feedback.  We are working on making the changes per your suggestion -- and we are working on getthing the build to pass in CI (it passes locally)

We preferred the output of MASON over HAL mainly due to client readability, and  it supports additional  h-factors.

**Comment by apotonick** [comment]
Very cool! Also, in case you haven't noticed, but I simplified some code in HAL on master. We should try to unify that in the Mason implementation! I can help.

**Comment by cabm** [comment]
We went ahead and updated the Mason code to work with the updated code, if you have any feedback please let us know. Thanks : )

**Comment by apotonick** [comment]
Cool! Can you please rebase it against master? It's very hard to read through the changed files otherwise.

**Comment by azurastar** [comment]
Should be all set now!

**Comment by cabm** [comment]
Great! Let us know if you have any other feedback prior to pulling it in.

**Pull request closed without merging**
