### PR TITLE
Enable JSONAPI#to_hash meta option 

### LINKED ISSUE #196: passing meta option does not work for JSONAPI
Calling to_hash on a representer with ("meta" => {"foo" => "bar"}} does not render the meta attributes.

It looks like the implementation partially exists but is missing actually making the call and returning the response: [https://github.com/apotonick/roar/blob/master/lib/roar/json/json_api.rb#L166](url)

### PR DESCRIPTION
**Pull request by myabc**
N.B. This removes incomplete implementation of `meta` field.

Fixes #196

### CODE REVIEW

**Comment by apotonick** [comment]
So you basically pass a hash instead of object as the `meta` data structure?

**Comment by myabc** [comment]
@apotonick this implements what's described in https://github.com/apotonick/roar#meta-data :

> Another way is to provide the complete meta data hash when rendering. You must not define any meta properties in the representer when using this approach.

I think allowing a `meta` field to be defined (with properties mapped to methods on the represented object) is also a good idea, but should be done in a separate commit/PR.

**Comment by apotonick** [comment]
Agreed. But shouldn't the meta object rather be a struct and have its own representer? I know the way it was implemented before wasn't great, but...?!?!

**Comment by myabc** [comment]
@apotonick why not support both?

**Comment by myabc** [comment]
Moved here: https://github.com/trailblazer/roar-jsonapi/pull/1

**Pull request closed without merging**
